import { useEffect, useMemo, useState } from 'react';
import StudentPortalLayout from '../components/student/StudentPortalLayout';
import { supabase } from '../lib/supabase';

type Result = { exam_subject_id: string; exam_name: string; subject_name: string; chapter_name: string | null; exam_date: string | null; max_marks: number; your_score: number | null; class_average: number | null };
const pct = (score: number | null, max: number) => max > 0 && score !== null ? Math.round((Number(score) / Number(max)) * 100) : 0;
export default function StudentPerformance() {
  const [rows, setRows] = useState<Result[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { supabase.rpc('fn_student_performance_summary' as never).then(({ data }) => { setRows((data ?? []) as Result[]); setLoading(false); }); }, []);
  const subjects = useMemo(() => Object.values(rows.reduce<Record<string, { name: string; your: number[]; average: number[] }>>((all, row) => { const item = all[row.subject_name] ?? { name: row.subject_name, your: [], average: [] }; item.your.push(pct(row.your_score, row.max_marks)); item.average.push(pct(row.class_average, row.max_marks)); all[row.subject_name] = item; return all; }, {})).map(item => ({ name: item.name, your: Math.round(item.your.reduce((a, b) => a + b, 0) / item.your.length), average: Math.round(item.average.reduce((a, b) => a + b, 0) / item.average.length) })), [rows]);
  const points = rows.slice().reverse().map((row, index) => `${rows.length < 2 ? 50 : index * (100 / (rows.length - 1))},${100 - pct(row.your_score, row.max_marks)}`).join(' ');
  return <StudentPortalLayout title="Performance"><div className="space-y-7"><section className="clay-card p-6 sm:p-8"><p className="text-sm font-bold text-primary">Your learning progress</p><h1 className="mt-1 text-3xl font-bold text-foreground">Performance</h1><p className="mt-2 text-muted">Your score compared with the class average for each subject.</p></section>{loading ? <section className="clay-card p-6 text-muted">Loading performance…</section> : rows.length === 0 ? <section className="clay-card p-6 text-muted">Marks will appear after your teacher enters them.</section> : <><section className="clay-card p-6"><div className="mb-5"><h2 className="font-bold text-foreground">Marks trend</h2><p className="mt-1 text-sm text-muted">Your percentage across recorded tests.</p></div><div className="h-44 rounded-2xl bg-teal-50/60 p-4"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full overflow-visible"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2.5" vectorEffect="non-scaling-stroke" className="text-primary" /></svg></div></section><section className="clay-card overflow-hidden"><div className="border-b border-border px-6 py-4"><h2 className="font-bold text-foreground">Subject scores</h2></div><div className="divide-y divide-border">{subjects.map(subject => <div key={subject.name} className="px-6 py-4"><div className="flex justify-between gap-4 text-sm"><p className="font-bold text-foreground">{subject.name}</p><p className="text-muted">You {subject.your}% · Average {subject.average}%</p></div><div className="mt-3 grid gap-2"><div className="h-2 rounded-full bg-stone-100"><div className="h-full rounded-full bg-primary" style={{ width: `${subject.your}%` }} /></div><div className="h-1.5 rounded-full bg-stone-100"><div className="h-full rounded-full bg-stone-400" style={{ width: `${subject.average}%` }} /></div></div></div>)}</div></section></>}</div></StudentPortalLayout>;
}
