import { useEffect, useMemo, useState } from 'react';
import StudentPortalLayout from '../components/student/StudentPortalLayout';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabase';

type Test = { id: string; exam_date: string | null; max_marks: number; chapter_name: string | null; subject_id: string; exam_id: string };
type Label = { id: string; name: string };
export default function StudentTests() {
  const { user } = useAuth(); const [tests, setTests] = useState<Test[]>([]); const [subjects, setSubjects] = useState<Label[]>([]); const [exams, setExams] = useState<Label[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { const load = async () => { if (!user?.schoolId) return; const { data: enrollment } = await supabase.from('class_enrollments').select('class_id').eq('student_id', user.id).is('deleted_at', null).order('enrolled_at', { ascending: false }).limit(1).maybeSingle(); if (!enrollment) { setLoading(false); return; } const { data } = await supabase.from('exam_subjects').select('id,exam_date,max_marks,chapter_name,subject_id,exam_id').eq('school_id', user.schoolId).eq('class_id', enrollment.class_id).is('deleted_at', null).order('exam_date'); const rows = (data ?? []) as Test[]; setTests(rows); const subjectIds = [...new Set(rows.map(row => row.subject_id))]; const examIds = [...new Set(rows.map(row => row.exam_id))]; const [subjectData, examData] = await Promise.all([subjectIds.length ? supabase.from('subjects').select('id,name').in('id', subjectIds) : Promise.resolve({ data: [] as Label[] }), examIds.length ? supabase.from('exams').select('id,name').in('id', examIds) : Promise.resolve({ data: [] as Label[] })]); setSubjects((subjectData.data ?? []) as Label[]); setExams((examData.data ?? []) as Label[]); setLoading(false); }; load(); }, [user?.id, user?.schoolId]);
  const today = new Date().toISOString().slice(0, 10); const lookup = (items: Label[], id: string) => items.find(item => item.id === id)?.name || 'Test'; const render = (items: Test[]) => items.length ? <div className="divide-y divide-border">{items.map(test => <div key={test.id} className="flex items-center justify-between gap-4 px-6 py-4"><div><p className="font-bold text-foreground">{lookup(exams, test.exam_id)}</p><p className="mt-1 text-sm text-muted">{lookup(subjects, test.subject_id)}{test.chapter_name ? ` · ${test.chapter_name}` : ''}</p></div><div className="text-right text-sm"><p className="font-bold text-foreground">{test.exam_date || 'Date not set'}</p><p className="mt-1 text-muted">Out of {test.max_marks}</p></div></div>)}</div> : <p className="p-6 text-muted">No tests here yet.</p>;
  const scheduled = useMemo(() => tests.filter(test => (test.exam_date || '') >= today), [tests, today]); const past = useMemo(() => tests.filter(test => (test.exam_date || '') < today), [tests, today]);
  return <StudentPortalLayout title="Tests"><div className="space-y-7"><section className="clay-card p-6 sm:p-8"><p className="text-sm font-bold text-primary">Your assessments</p><h1 className="mt-1 text-3xl font-bold text-foreground">Tests</h1><p className="mt-2 text-muted">Keep track of upcoming and completed tests.</p></section>{loading ? <section className="clay-card p-6 text-muted">Loading tests…</section> : <><section className="clay-card overflow-hidden"><div className="border-b border-border px-6 py-4"><h2 className="font-bold text-foreground">Scheduled tests</h2></div>{render(scheduled)}</section><section className="clay-card overflow-hidden"><div className="border-b border-border px-6 py-4"><h2 className="font-bold text-foreground">Past tests</h2></div>{render(past)}</section></>}</div></StudentPortalLayout>;
}
